apiVersion: v1
kind: Service
metadata:
  name: data-updater-service
spec:
  type: LoadBalancer
  selector: 
    app: data-updater
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5000
