apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-base-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/guysh/InvestingProject/DataBase
  reclaimPolicy: Retain
